version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: inferth-app
    restart: always
    ports:
      - "80:8000"   # Frontend/API
      - "9005:9005" # Tracker TCP Server
    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:kwaramba1@db:5432/inferth
      - REDIS_URL=redis://redis:6379/0
      - PORT=8000
    depends_on:
      - db
      - redis
    networks:
      - track-net

  db:
      image: postgres:15-alpine
      container_name: inferth-db
      restart: always
      environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=kwaramba1
        - POSTGRES_DB=inferth
      volumes:
        - postgres_data:/var/lib/postgresql/data
      networks:
        - track-net

  redis:
    image: redis:alpine
    container_name: inferth-redis
    restart: always
    networks:
      - track-net

networks:
  track-net:
    driver: bridge

volumes:
  postgres_data:
